### ISSUE TITLE
first search error

### ISSUE THREAD

**Issue by QGB** [nicholaskajoh/devsearch#8]
File "/www/devsearch/views.py", line 19, in <listcomp>
@app.route('/search')
def search():
    start_time = time.time()
 
    # get autocomplete data
    autocomplete_data = [qo.q for qo in Query.objects.limit(250).order_by('-frequency')]
 
    q = request.args.get('q', default=None)
    p = int(request.args.get('p', default=1))
    pages = None
    pages_count = 0
RuntimeError: generator raised StopIteration

**Comment by nicholaskajoh** [comment]
Please see: https://github.com/nicholaskajoh/devsearch/issues/7#issuecomment-533785935.

**Comment by QGB** [comment]
I am using python3.7 
 this problem cause by：
https://stackoverflow.com/questions/51398724/mongoengine-runtimeerror-generator-raised-stopiteration
